import { defineConfig, type OxlintConfig } from "oxlint";

export default defineConfig({
  options: {
    reportUnusedDisableDirectives: "warn",
    typeAware: true,
    typeCheck: false,
  },
  plugins: [
    "import",
    // TODO: enable and clean up violations of these plugins
    "effecttsgo",
    // "typescript",
    "node",
    "unicorn",
    "oxc",
  ],
  ignorePatterns: [
    "submodules/**",
    "packages/alchemy/test/**",
    "packages/alchemy-test/**",
    "examples/**",
    "demos/**",
    "**/fixtures/**",
    "**/*.test.ts",
  ],
  rules: {
    "require-yield": "off",
    "no-irregular-whitespace": "off",
    "typescript/no-misused-new": "off",
    // TODO: fix all violations of this
    "typescript/no-non-null-asserted-optional-chain": "off",
    "effecttsgo/any-unknown-in-error-context": "off",
    "effecttsgo/unstable-api-usage": "off",
    "effecttsgo/instance-of-schema": "warn",
    "effecttsgo/nested-effect-gen-yield": "warn",
    "effecttsgo/new-schema-class": "warn",
    "effecttsgo/schema-sync": "warn",
    "effecttsgo/service-not-as-class": "warn",
    "effecttsgo/unnecessary-arrow-block": "warn",
    "effecttsgo/extends-native-error": "warn",
    "effecttsgo/unnecessary-fail-yieldable-error": "warn",
    "effecttsgo/flat-map-conditional-to-filter-or-fail": "off",
    "effecttsgo/multiple-catch-tag": "warn",
    "effecttsgo/catch-to-or-else-succeed": "warn",
    "effecttsgo/missed-pipeable-opportunity": "warn",
    "effecttsgo/unnecessary-pipe-chain": "warn",
    "effecttsgo/catch-to-ignore": "warn",
    "effecttsgo/unnecessary-effect-gen": "warn",
    "effecttsgo/catch-all-tag-dispatch-to-catch-tag": "warn",
    "effecttsgo/catch-all-to-map-error": "warn",
    "effecttsgo/catch-chain-to-first-success-of": "warn",
    "effecttsgo/catch-conditional-refail-to-catch-if": "warn",
    "effecttsgo/catch-die-to-or-die": "warn",
    "effecttsgo/catch-if-tag-to-catch-tag": "warn",
    "effecttsgo/catch-refail-to-tap-error": "warn",
    "effecttsgo/catch-tag-to-catch-reason": "warn",
    "effecttsgo/provide-layer-succeed-to-provide-service": "warn",
    "effecttsgo/timeout-catch-tag-to-timeout-or-else": "warn",
    "effecttsgo/effect-fn-opportunity": "warn",
    "effecttsgo/unnecessary-pipe": "warn",
    "effecttsgo/redundant-or-die": "warn",
    "effecttsgo/map-some-to-as-some": "warn",
    "effecttsgo/flat-map-ignored-param-to-and-then": "warn",
    "effecttsgo/sync-to-succeed": "warn",
    "effecttsgo/option-match-to-from-option": "warn",
    "effecttsgo/flat-map-to-map": "warn",
    "effecttsgo/effect-map-flatten": "warn",
    "effecttsgo/acquire-release-disposable": "warn",
    "effecttsgo/effect-do-notation": "warn",
    "effecttsgo/effect-map-void": "warn",
    "effecttsgo/match-effect-to-map-both": "warn",
    "effecttsgo/match-effect-to-match": "warn",
    "effecttsgo/missing-effect-service-dependency": "warn",
    "effecttsgo/prefer-schema-type-property": "warn",
    "effecttsgo/prefer-succeed-some-or-none": "warn",
    "effecttsgo/race-first-with-sleep-to-timeout": "warn",
    "effecttsgo/redundant-map-error": "warn",
    "effecttsgo/redundant-schema-tag-identifier": "warn",
    "effecttsgo/run-of-exit-to-run-exit": "warn",
    "effecttsgo/schema-struct-with-tag": "warn",
    "effecttsgo/schema-union-of-literals": "warn",
    "effecttsgo/unnecessary-typeof-type": "warn",
  },
} satisfies OxlintConfig);
